version: '3.7'

services:
  web:
    build: .
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    depends_on:
      - elasticsearch
    volumes:
      - .:/usr/src/app/cards
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet
volumes:
  esdata:
networks:
  esnet:
